name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.type != 'Bot' }}
    steps:
      - name: Assign PR to Author
        env:
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
        run: gh pr edit $PRNUM --add-assignee $PRAUTHOR
