name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to Author
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          PRAUTHOR: ${{ github.event.pull_request.user.login }}
          PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
        run: |
          if [ "$PR_AUTHOR_TYPE" != "Bot" ]
          then
            gh pr edit $PRNUM --add-assignee $PRAUTHOR
          fi
