name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR to Author
      - uses: kentaro-m/auto-assign-action@v1.2.1
        with:
          addAssignees: 'author'
