name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.type != 'Bot' }}
    steps:
      - name: Assign PR to Author
        env:
          GH_REPO: ${{ github.repository }}
          PRNUM: ${{ github.event.pull_request.number }}
        run: gh pr edit $PRNUM --add-assignee $PRAUTHOR
  if_error_or_failure:
    runs-on: ubuntu-latest
    if: >-
      (github.event.state == 'error' || github.event.state == 'failure')
    steps:
      - env:
          DESCRIPTION: ${{ github.event.description }}
        run: |
          echo The status is error or failed: $DESCRIPTION
