name: PR Automation
on:
  pull_request_target:
    types: [ready_for_review, opened, reopened]

permissions:
  contents: none
  issues: write
  pull-requests: write

jobs:
  pr-auto:
    runs-on: ubuntu-latest
    steps:
      - name: lint pr
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.AUTOMATION_TOKEN }}
          PRID: ${{ github.event.pull_request.node_id }}
          PRBODY: ${{ github.event.pull_request.body }}
          PRNUM: ${{ github.event.pull_request.number }}
          PRHEAD: ${{ github.event.pull_request.head.label }}
          PRAUTHOR: ${{ github.event.pull_request.user.login }}
          PR_AUTHOR_TYPE: ${{ github.event.pull_request.user.type }}
        if: "!github.event.pull_request.draft"
        run: |
          commentPR () {
            gh pr comment $PRNUM -b "${1}"
          }

          if [ $(wc -c <<<"$PRBODY") -lt 10 ]
          then
            commentPR "Thanks for the pull request! We're a small team and it's helpful to have context around community submissions in order to review them appropriately. Our automation has closed this pull request since it does not have an adequate description. Please edit the body of this pull request to describe what this does, then reopen it."
            exit 0
          fi
